INSERT INTO article(id,title,body) VALUES(1,'飞花令（江）','江南好，风景旧曾谙。日出江花红胜火，春来江水绿如蓝。 ');
INSERT INTO article(id,title,body) VALUES(2,'飞花令（江）','月落乌啼霜满天，江枫渔火对愁眠。');
INSERT INTO article(id,title,body) VALUES(3,'飞花令（江）','竹外桃花三两枝,春江水暖鸭先知。 ');
INSERT INTO article(id,title,body) VALUES(4,'飞花令（江）','天门中断楚江开，碧水东流至此回。');
INSERT INTO article(id,title,body) VALUES(5,'飞花令（江）','迟日江山丽，春风花草香。');
INSERT INTO article(id,title,body) VALUES(6,'飞花令（江）','孤舟蓑笠翁，独钓寒江雪。');
INSERT INTO article(id,title,body) VALUES(7,'飞花令（江）','野径云俱黑，江船火独明。');
INSERT INTO article(id,title,body) VALUES(8,'飞花令（江）','野旷天低树，江清月近人。');
INSERT INTO article(id,title,body) VALUES(9,'飞花令（江）','至今思项羽，不肯过江东。');
INSERT INTO article(id,title,body) VALUES(10,'飞花令（江)','朝辞白帝彩云间，千里江陵一日还。');
INSERT INTO article(id,title,body) VALUES(11,'飞花令（楼)','危楼高百尺，手可摘星辰。');
INSERT INTO article(id,title,body) VALUES(12,'飞花令（楼)’,’小楼昨夜又东风,故国不堪回首月明中。');
INSERT INTO article(id,title,body) VALUES(13,'飞花令（楼)','昨夜西风凋碧树,独上高楼,望尽天涯路。');
INSERT INTO article(id,title,body) VALUES(13,'飞花令（楼）','昨夜西风凋碧树,独上高楼,望尽天涯路。');
INSERT INTO article(id,title,body) VALUES(14,'飞花令（楼）','昔人已乘黄鹤去,此地空余黄鹤楼。 ');
INSERT INTO article(id,title,body) VALUES(15,'飞花令（楼）','故人西辞黄鹤楼,烟花三月下扬州。');
INSERT INTO article(id,title,body) VALUES(16,'飞花令（楼）','昨夜星辰昨夜风,画楼西畔桂堂东。');
INSERT INTO article(id,title,body) VALUES(17,'飞花令（楼）','欲穷千里目,更上一层楼。');
INSERT INTO article(id,title,body) VALUES(18,'飞花令（楼）','山外青山楼外楼,西湖歌舞几时休。');
INSERT INTO article(id,title,body) VALUES(19,'飞花令（楼）','南朝四百八十寺，多少楼台烟雨中。');
INSERT INTO article(id,title,body) VALUES(20,'飞花令（楼）','少年不识愁滋味，爱上层楼。');
INSERT INTO article(id,title,body) VALUES(21,'飞花令（马）','夜阑卧听风吹雨，铁马冰河入梦来。');
INSERT INTO article(id,title,body) VALUES(22,'飞花令（马）','乱花渐欲迷人眼，浅草才能没马蹄。');
INSERT INTO article(id,title,body) VALUES(23,'飞花令（马）','草枯鹰眼疾，雪尽马蹄轻。');
INSERT INTO article(id,title,body) VALUES(24,'飞花令（马）','枯藤老树昏鸦，小桥流水人家，古道西风瘦马。');
INSERT INTO article(id,title,body) VALUES(25,'飞花令（马）','挥手自兹去，萧萧班马鸣。 ');
INSERT INTO article(id,title,body) VALUES(26,'飞花令（马）','云横秦岭家何在？ 雪拥南关马不前。');
INSERT INTO article(id,title,body) VALUES(27,'飞花令（马）','葡萄美酒夜光杯，欲饮琵琶马上催。');
INSERT INTO article(id,title,body) VALUES(28,'飞花令（马）','竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。 ');
INSERT INTO article(id,title,body) VALUES(29,'飞花令（马）','马作的卢飞快，弓如霹雳弦惊。');
INSERT INTO article(id,title,body) VALUES(30,'飞花令（马）','春风得意马蹄疾，一日看尽长安花。');
INSERT INTO article(id,title,body) VALUES(31,'飞花令（心）','身无彩凤双飞翼，心有灵犀一点通。 ');
INSERT INTO article(id,title,body) VALUES(32,'飞花令（心）','臣心一片磁针石，不指南方不肯休。');
INSERT INTO article(id,title,body) VALUES(33,'飞花令（心）','谁言寸草心，报得三春晖。');
INSERT INTO article(id,title,body) VALUES(34,'飞花令（心）','感时花溅泪，恨别鸟惊心。');
INSERT INTO article(id,title,body) VALUES(35,'飞花令（心）','洛阳亲友如相问，一片冰心在玉壶。');
INSERT INTO article(id,title,body) VALUES(36,'飞花令（心）','此情无计可消除，才下眉头，却上心头。');
INSERT INTO article(id,title,body) VALUES(37,'飞花令（心）','烈士暮年，壮心不已。');
INSERT INTO article(id,title,body) VALUES(38,'飞花令（心）','嫦娥应悔偷灵药，碧海青天夜夜心。');
INSERT INTO article(id,title,body) VALUES(39,'飞花令（心）','我寄愁心与明月，随风直到夜郎西。');
INSERT INTO article(id,title,body) VALUES(40,'飞花令（心）','时人不识余心乐，将谓偷闲学少年。');
INSERT INTO article(id,title,body) VALUES(41,'飞花令（雪） ','草枯鹰眼疾,雪尽马蹄轻。 ');
INSERT INTO article(id,title,body) VALUES(42,'飞花令（雪） ','大漠沙如雪,燕山月似钩。');
INSERT INTO article(id,title,body) VALUES(43,'飞花令（雪） ','云横秦岭家何在？雪拥蓝关马不前。  ');
INSERT INTO article(id,title,body) VALUES(44,'飞花令（雪） ','燕山雪花大如席,纷纷吹落轩辕台。 ');
INSERT INTO article(id,title,body) VALUES(45,'飞花令（雪） ','梅须逊雪三分白,雪却输梅一段香。');
INSERT INTO article(id,title,body) VALUES(46,'飞花令（雨）','青箬笠,绿蓑衣,斜风细雨不须归');
INSERT INTO article(id,title,body) VALUES(47,'飞花令（雨）','沾衣欲湿杏花雨,吹面不寒杨柳风。');
INSERT INTO article(id,title,body) VALUES(48,'飞花令（雨）','渭城朝雨亦轻尘,客舍青青柳色新。');
INSERT INTO article(id,title,body) VALUES(49,'飞花令（雨）','南朝四百八十寺,多少楼台烟雨中。');
INSERT INTO article(id,title,body) VALUES(50,'飞花令（雨）','好雨知时节,当春乃发生。');
INSERT INTO article(id,title,body) VALUES(51,'飞花令（花）','夜来风雨声，花落知多少。');
INSERT INTO article(id,title,body) VALUES(52,'飞花令（花）','何须浅碧深红色，自是花中第一流。');
INSERT INTO article(id,title,body) VALUES(53,'飞花令（花）','人闲桂花落，夜静春山空。');
INSERT INTO article(id,title,body) VALUES(54,'飞花令（花）','感时花溅泪，恨别鸟惊心。');
INSERT INTO article(id,title,body) VALUES(55,'飞花令（花）','花谢花飞花满天， 红消香断有谁怜。');
INSERT INTO article(id,title,body) VALUES(56,'飞花令（月）','明月几时有，把酒问青天。');
INSERT INTO article(id,title,body) VALUES(57,'飞花令（月）','月下飞天镜，云生结海楼。');
INSERT INTO article(id,title,body) VALUES(58,'飞花令（月）','春宵一刻值千金，花有清香月有阴。');
INSERT INTO article(id,title,body) VALUES(59,'飞花令（月）','小时不识月，呼作白玉盘。');
INSERT INTO article(id,title,body) VALUES(60,'飞花令（月）','我本将心向明月，奈何明月照沟渠。');